name: Build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/LICENSE'
      - '**/README.md'
      - '**/build.yml'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Nuget Restore
        run: nuget restore

      #############
      ### BUILD ###
      #############

      - name: Build Studio
        shell: pwsh
        run: .\build.ps1

      - name: Prepare Artifacts
        run: |
          mkdir output-net8\\AnimeStudio-net8-${{ github.sha }}
          xcopy /E /I /Y .\dist\net8.0-windows\* output-net8\\AnimeStudio-net8-${{ github.sha }}\\
          mkdir output-net9\\AnimeStudio-net9-${{ github.sha }}
          xcopy /E /I /Y .\dist\net9.0-windows\* output-net9\\AnimeStudio-net9-${{ github.sha }}\\

      - name: Upload .NET 8 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnimeStudio-net8
          path: output-net8

      - name: Upload .NET 9 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnimeStudio-net9
          path: output-net9